name: Automation Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test_ui:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start app with Docker Compose
      run: |
          docker compose -f ./notes_app/docker-compose.yml up -d
          echo "Checking running containers..."
          docker ps

    - name: Wait for server to Start
      run: |
         echo "Waiting for web server..."
         for i in {1..30}; do
          if curl -s http://localhost:4000/ > /dev/null; then
            echo "Server is up!"
            exit 0
          fi
          echo "App not ready yet... retry ($i/30)"
          sleep 4
         done
         echo "Server did not start in time."
         docker compose -f ./notes_app/docker-compose.yml logs
         exit 1

    - name: Run Playwright tests
      run: npm run test-ui

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Teardown Docker
      if: always()
      run: docker compose -f ./notes_app/docker-compose.yml down --volumes --remove-orphans

  test_api:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      MONGOMS_DISABLE_POSTINSTALL: "1"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run API tests
      run: npm run test-api
  
  test_db:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      MONGOMS_DISABLE_POSTINSTALL: "1"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run DB tests
      run: npm run test-db
